language: python

python:
  - "3.4"
  - "3.5"

addons:
  apt:
    packages:
      - xdg-utils
      - xfce4

before_script:
  - "export DISPLAY=99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

script: "make test"
